### ISSUE TITLE
File component

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/denhaag#111]
The [Design System](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=2334%3A3) defines a File Component. We should assess whether or not this requires a a component in our component library.

![image](https://user-images.githubusercontent.com/24610692/111868068-1832df00-8978-11eb-93f8-52055ea4df70.png)

**Comment by ogjtech** [comment]
Looks to me like this could just be a Button or a Link component that points to a URL where the file can be downloaded and/or opened. I do not think we should define another component for this. It adds no extra behaviour and the special icon in this button can just be supplied as an `Icon` component of some sort.
