### ISSUE TITLE
Design: Chat

### ISSUE THREAD

**Issue by mjcarsjens** [nl-design-system/denhaag#127]
[Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=2284%3A13092)

**Comment by mjcarsjens** [comment]
@Gemeente-DenHaag/mdh-rysst we should discuss and identify which underlying components are necessary to implement this, and add stories of components which we are still missing (for example: `Avatar`-component).

**Comment by YourivHDenHaag** [comment]
No longer applicable
