### ISSUE TITLE
Design: Datepicker

### ISSUE THREAD

**Issue by mjcarsjens** [nl-design-system/denhaag#128]
[Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1681%3A7756).

**Comment by mjcarsjens** [comment]
Awaiting discussion/design in Figma.

**Comment by Robbert** [comment]
This component is an implementation of the Date picker component in NL Design System: nl-design-system/backlog#35

**Comment by bddjong** [comment]
Same as https://github.com/nl-design-system/denhaag/issues/479
