### ISSUE TITLE
Missing Component: InputAdornment

### ISSUE THREAD

**Issue by DanielvanVliet** [nl-design-system/denhaag#22]
In order to display icons within a Textfield, we will need the [InputAdornment ](https://material-ui.com/components/text-fields/#input-adornments)component.

**Tasks**
- [ ] Added the InputAdornment component
- [ ] Added a story with the InputAdornmentComponent in a TextField component (Both imported from nlds-react-components)

**Comment by bddjong** [comment]
No longer relevant without MUI
