### ISSUE TITLE
Check the order of properties in css files with a linter

### ISSUE THREAD

**Issue by joostvanviegen** [nl-design-system/denhaag#220]
Right now we don't have any checks on the css files. Because of this there is some inconsistency in the order of css properties of some components.

In order to fix this we will need to implement either [stylelint-order](https://github.com/hudochenkov/stylelint-order) or [postcss-sorting](https://github.com/hudochenkov/postcss-sorting).
 
### Acceptance criteria
- [x] Choose a linter plugin
- [x] Add linter plugin as dependency
- [x] Configure plugin if needed
- [x] Fix existing stylesheets with linter

**Comment by bddjong** [comment]
This was resolved by #540
