### ISSUE TITLE
Button has shadow on mobile in some cases

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/denhaag#265]
![image](https://user-images.githubusercontent.com/24610692/123073058-5e378d00-d416-11eb-9977-5129776a8b96.png)

When testing the button component on mobile in the storybook [staging environent](http://dhreactstorybook-staging.azurewebsites.net/?path=/story/components-input-button--default-story), it will display a shadow in some cases after clicking. This might be a MUI style for mobile that we haven't overwritten yet.

![image](https://user-images.githubusercontent.com/24610692/124926626-0bf19100-dffe-11eb-877c-fb5a02927825.png)

**Comment by DanielvanVliet** [comment]
Shadow is added when :active is manually selected in dev console.
