### ISSUE TITLE
Include design-tokens-common and design-tokens-proprietary in design-tokens-components

### ISSUE THREAD

**Issue by mjcarsjens** [nl-design-system/denhaag#309]
There are several use-cases in which you would only want the `design-tokens-common` or `design-tokens-proprietary` packages and not all design token packages.
This is however not the case for `design-tokens-components`. We currently see no use-case for why you would want the component design tokens without the other two packages. Because of this we should also include the `design-tokens-common` and `design-tokens-proprietary` packages in the `design-tokens-components` packages. This way someone who wants all the design tokens can simply include only one dependency instead of 3.

**Comment by bddjong** [comment]
Tokens are already in `/components/dist`, package json should have other tokens packages as regular dependency instead of devDependency
