### ISSUE TITLE
Link issues

### ISSUE THREAD

**Issue by mritense** [nl-design-system/denhaag#386]
### User story

As a developer using the component library, I would like to be able to use the link component

### Describe the solution you'd like

I would like the link component (under Navigation on Storybook) to be included in the component library

### Describe alternatives you've considered

Styling html a element manually

**Comment by bddjong** [comment]
As of version `0.2.3-alpha.29`, the link is still not available when adding the `denhaag-component-library` meta package, even though it's been added to its exports. Should investigate and fix.

**Workaround**
Use `@gemeente-denhaag/link` as extra dependency.

**Comment by bddjong** [comment]
Additionally, the link needs a component prop which allows the user to pass a router library link to handle navigation
