### ISSUE TITLE
List Issues

### ISSUE THREAD

**Issue by mjcarsjens** [nl-design-system/denhaag#402]
- [ ] a11y issue: ListSubHeader uses a `<p>` component inside a `<ul>`
- [ ] ListItem right icon is positioned using `position: absolute;`. When the screen is too small or we are using a inline container the icon will overlap the text (see screenshot below).

![List #0](https://user-images.githubusercontent.com/12658988/133562407-4f7e9352-a31a-4990-9c2f-62dbd7a541f9.png)

**Comment by bddjong** [comment]
If it's a lot of effort, we'll leave these issues as is and fix them when the component is rewritten without Material UI
