### ISSUE TITLE
Alert (warning): color contrast a11y issue text and background

### ISSUE THREAD

**Issue by mjcarsjens** [nl-design-system/denhaag#407]
The contrast between the text content and the background for our warning Alert is insufficient: 2.94 instead of 4.5

https://nl-design-system.github.io/denhaag/?path=/story/components-data-display-alerts--warning
![image](https://user-images.githubusercontent.com/12658988/133571673-44499f4f-3404-4737-adfe-eb6666b98cad.png)

**Comment by bddjong** [comment]
Figma has an updated darker text color (orange/5), but this is the same as the action button hover color. Design needs to be updated before we can fix this: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=0%3A1

Icon in the design still has the old color, so contrast requirements aren't met.

**Comment by bddjong** [comment]
Resolved
