### ISSUE TITLE
Alert: Close button no hover style

### ISSUE THREAD

**Issue by mjcarsjens** [nl-design-system/denhaag#410]
The close button for the alerts has no hover color. The `--denhaag-icon-button-hover-color` CSS variable is set to the same value as `--denhaag-icon-button-color` for all variants.

**Comment by bddjong** [comment]
Comment in figma https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=0%3A1

**Comment by bddjong** [comment]
Close buttons on the alert have no hover color per design.
