### ISSUE TITLE
ListItem weird focus behaviour

### ISSUE THREAD

**Issue by mjcarsjens** [nl-design-system/denhaag#427]
When clicking a ListItem with `actionType` set to `action` the focus border will in fact appear around the whole ListItem, suggesting to the user something should have happened when this is certainly not the case. Same goes the other way round, the icon can get a focus border when `actionType` is `nav`.

**Comment by mjcarsjens** [comment]
Same goes for when a listitem actually doesn't have an action at all.

**Comment by bddjong** [comment]
This is slightly related to #345 (Inconsistent focus behavior)
