### ISSUE TITLE
Keyboard a11y not being tested properly

### ISSUE THREAD

**Issue by mjcarsjens** [nl-design-system/denhaag#428]
The keyboard accessibility is not being tested properly. When calling `cy.get('...').type('{enter}')` what it actually does is the following:
click the element to receive focus, and then type enter. The click being registered is actually the focus click instead of the enter typing. When running `cy.get('...').focus().type('{enter}')` you will see that the `onClick` is actually not called at all. 

Weirdly enough, this is the case for natively clickable element (e.g. `a` and `button` tags, but when a non-natively-clickable element is made focusable (with `tabindex="0"`) and clickable (e.g. our `Listitem` component makes a `li` tag clickable) the `cy.get('...').focus().type('{enter'})` does in fact call the `onClick` function. Need to find a way to make keyboard behavior properly testable. 

Relevant cypress issue describing typing `enter` does not in fact call a `onClick`: https://github.com/cypress-io/cypress/issues/8267

**Comment by bddjong** [comment]
This plugin could solve the issue: https://github.com/dmtrKovalenko/cypress-real-events#readme

Using `.realClick()`
