### ISSUE TITLE
OpenForms Flatpickr style overwrite to support design tokens

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/denhaag#479]
### User story

As a developer / organisation, I want to be able to style the date picker component in OpenForms with design tokens to match my organisation theme. 

### Description

OpenForms uses [FlatPickr](https://flatpickr.js.org/) for its date picker input. This means the styling is encapsulated in a node module, instead of in the open forms source. 

### Describe alternatives you've considered

Overwriting the Flatpickr CSS to use css variables referring to design tokens with fallback values. This however leads to another coupling with a third party library that would need to be maintained. 

### Additional context

![image](https://user-images.githubusercontent.com/24610692/140495170-1201236d-c146-4b7d-a4a1-0b420e272de5.png)

**Comment by mjcarsjens** [comment]
For now: look into other datepickers available on my PC otherwise, wait for implementation from Maykin/Utrecht.
