### ISSUE TITLE
refinement: Remove MUI from components

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/denhaag#495]
Create issues for refactoring to remove dependency on MUI from:

- [x] Button
- [ ] Card
- [ ] Tabs
- [ ] Avatar 
- [ ] Divider
- [ ] Timeline
- [ ] IconButton
- [x] Form Inputs (some already have open issues, make sure the remove MUI dependency is part of the issue requirements)
- [ ] StylesProvider could be removed if it's not required for anything else

**Comment by YourivHDenHaag** [comment]
Done
