### ISSUE TITLE
Design: Checkbox

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#55]
The Checkbox component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1450%3A4570).

## Acceptance criteria
**Variants implemented**
- [x] Active
- [x] Inactive

**States implemented**
- [x] Normal
- [x] Hover
- [x] Disabled
- [x] Error
- [x] Focus

**CheckboxGroup (FormGroup Component)**
- [x] Each checkbox group can have a header label
- [x] Each checkbox group can have a help text
- [ ] Each checkbox group can have an error text which should appear in conjunction with all checkboxes in the group having the Error state (which replaces the help text)

**Requirements**
- [x] Checkmark provided as SvgIcon, not default MaterialUI checkmark
- [x] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1450%3A4570)  requirements are met
- [x] Classes use the BEM naming convention
- [x] Design tokens are identified > proposed > implemented
- [x] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.
- [x] Storybook shows HTML code snippet (with classes and accessibility suggestions) (Depends on #267 )

**Comment by Robbert** [comment]
This component is an implementation of the Checkbox component in NL Design System: nl-design-system/backlog#64

**Comment by GewoonMaarten** [comment]
Disabled styling is a bit broken, the colors are not correct. And hover shows the incorrect colors and cursor
