### ISSUE TITLE
Design: Select

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#57]
The Select component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1683%3A6916).

## Acceptance criteria
**States implemented**
- [ ] Normal
- [ ] Active
- [ ] Disabled
- [ ] Error
- [ ] Focus

**Options**
For the options default browser options are used. (`native` prop)
**Requirements**
- [ ] When no value is selected a optional placeholder text can be show, otherwise the selected value.
- [ ] For the disabled Select no placeholder will be shown.
- [ ] On error an optional error icon can be shown.
- [ ] A label has to always be shown above a Select.
- [ ] An optional helper text can be shown below a Select.
- [ ] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1683%3A6916) requirements are met
- [ ] Classes use the BEM naming convention
- [ ] Design tokens are identified > proposed > implemented
- [ ] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by Robbert** [comment]
This component is an implementation of the Dropdown listbox component in NL Design System: nl-design-system/backlog#34
