### ISSUE TITLE
Design: Text field

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#59]
The TextField component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1%3A1653).

## Acceptance criteria
**Variants implemented**
- [x] Single line
- [ ] Multi line

**States implemented**
- [x] Normal
- [x] Hover
- [x] Disabled
- [x] Error
- [x] Focus

**Components**
- [ ] Optional placeholder text
- [ ] Optional helper text
- [ ] Required label
- [ ] Optional error text
- [ ] For the multi-line variant an optional character counter can be added

**Icon support**
- [x] An optional trailing icon can be added in the text filed
- [x] An optional error icon can be added in the text field (when a trailing icon is shown, the error icon will appear before it)

For this we have to use the MUI `InputAdornment` component

**Requirements**
- [ ] The optional character counter should be supplied a max-length and update the current amount of characters when typing.
- [x] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1%3A1653)  requirements are met
- [x] Classes use the BEM naming convention
- [x] Design tokens are identified > proposed > implemented
- [x] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by Robbert** [comment]
This component is an implementation of the Text input component in NL Design System: nl-design-system/backlog#5
