### ISSUE TITLE
Design: Toggle

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#60]
The Switch component (called Toggle in the design) needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1681%3A7439).

## Acceptance criteria
**Variants implemented**
- [ ] Inactive
- [ ] Active

**States implemented**
- [ ] Normal
- [ ] Hover
- [ ] Disabled
- [ ] Focus

**Requirements**
- [ ] A label can be shown above the toggle
- [ ] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1681%3A7439)  requirements are met
- [ ] Classes use the BEM naming convention
- [ ] Design tokens are identified > proposed > implemented
- [ ] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by Robbert** [comment]
This component is an implementation of the Switch component in NL Design System: nl-design-system/backlog#33
