### ISSUE TITLE
Design: Badges

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#62]
The Badge component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1540%3A4477).

## Acceptance criteria
**Components implemented**
- [x] Badge with number (uses a dot badge internally)
- [x] Dot badge

**Requirements**
- [x] The badge should only be visible when the count is larger than 1
- [x] When the count is larger than 999 it should display 999+ in the Badge with number variant
- [x] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1540%3A4477)  requirements are met
- [x] Classes use the BEM naming convention
- [x] Design tokens are identified > proposed > implemented
- [x] Code snippet showing HTML structure with BEM classes in storybook
- [x] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by mjcarsjens** [comment]
Awaiting response in design

**Comment by Robbert** [comment]
This component is an implementation of two components in NL Design System: Counter badge component (nl-design-system/backlog#7) and Dot indicator component (nl-design-system/backlog#98)

**Comment by bddjong** [comment]
The badge should only be visible when the count is larger than 1
 When the count is larger than 999 it should display 999+ in the Badge with number variant

These requirements sound like they are up to the user to determine whether or not they wish to implement it.
