### ISSUE TITLE
Design: Text + image

### ISSUE THREAD

**Issue by jeroenkel** [nl-design-system/denhaag#646]
Figma: https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=8553%3A29678

**Comment by Robbert** [comment]
The HTML could use [`<figure>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) and [`<figcaption>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption) elements.
