### ISSUE TITLE
Design: Tag

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#66]
The Tag component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1043%3A184).

## Acceptance criteria
**Variants implemented**
- [ ] Red 
- [ ] Orange
- [ ] Green
- [ ] Blue
- [ ] Grey

**Note**: the names of these variants should be discussed. Using colors in the variant names is something we should not do, these should be named by their use not by their visual appearance (e.g. `Error`, `Warning` etc.).

**Requirements**
- [ ] Support for `aria-label` HTML prop
- [ ] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1043%3A184)  requirements are met
- [ ] Classes use the BEM naming convention
- [ ] Design tokens are identified > proposed > implemented
- [ ] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by mjcarsjens** [comment]
Waiting on response to input on the design

**Comment by Robbert** [comment]
This component is an implementation of the Status badge component in NL Design System: nl-design-system/backlog#6
