### ISSUE TITLE
Design: Alerts

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#67]
The Alert component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1470%3A10). 
For the implementation we will not be using a Material-UI component, instead we will use our own HTML implementation together with our already existing components. For this we will use the stencil component provided below as inspiration.

The accessibility side of the implementation should be researched and carefully tested.

## Acceptance criteria
**Variants implemented**
- [ ] Base
- [x] Alert
- [x] Info
- [x] Success
- [x] Warning

**Button support**
- [x] Optional close button
- [x] Optional action button

**Icon support**
- [x] Icon can be provided

**Animations**
For now we will deliver this component without animations. Animations will be added at a later date.

**Requirements**
- [x] Size of the Alert is based on the context it is placed in
- [x] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1470%3A10)  requirements are met
- [x] Classes use the BEM naming convention
- [x] Design tokens are identified > proposed > implemented
- [x] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.
- [x] Storybook shows HTML code snippet (with classes and accessibility suggestions) (Depends on #267)

**Comment by mjcarsjens** [comment]
Waiting for definition of animations in design

**Comment by Robbert** [comment]
This component is an implementation of the Notification component in NL Design System: nl-design-system/backlog#9

**Comment by mjcarsjens** [comment]
[mdh-alert_STENCIL-INSPIRATIE.zip](https://github.com/Gemeente-DenHaag/denhaag-component-library/files/6670589/mdh-alert_STENCIL-INSPIRATIE.zip)
