### ISSUE TITLE
Design: Modal

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#68]
The Modal component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=221%3A32).

## Acceptance criteria
**Variants implemented**
- [ ] Base

**Required parts**
- [ ] Title
- [ ] Close Icon
- [ ] Text

**Button support**
- [ ] Optional Primary Action Button
- [ ] Optional Secondary Action Button

**Requirements**
- [ ] The Modal should overlay the content
- [ ] No interaction should be possible outside the Modal until it is closed
- [ ] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=221%3A32)  requirements are met
- [ ] Classes use the BEM naming convention
- [ ] Design tokens are identified > proposed > implemented
- [ ] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by Robbert** [comment]
This component is an implementation of the Modal dialog component in NL Design System: nl-design-system/backlog#66
