### ISSUE TITLE
Design: Navigation links

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#69]
The Navigation Link component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1485%3A1156).

## Acceptance criteria
**Variants implemented**
- [x] Text only
- [x] Icon left
- [x] Icon right

**States implemented**
- [x] Normal
- [x] Hover
- [x] Disabled
- [x] Focus

**Requirements**
- [x] Icon is placed as a `prop` not in the children
- [x] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1485%3A1156) requirements are met
- [x] Classes use the BEM naming convention
- [x] Design tokens are identified > proposed > implemented
- [x] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by Robbert** [comment]
This component is an implementation of the Link component in NL Design System: #118
