### ISSUE TITLE
Design: Form navigation

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#72]
The Form Navigation component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1627%3A6507).

## Acceptance criteria
**Variants implemented**
- [ ] Desktop: Same as Stepper but with added Error option
- [ ] Mobile: Same stickied header as with the Anchor Navigation, but in the Drawer the Desktop version of this component

**States implemented**
- [ ] Hover
- [ ] Error

**Note:** What about a focus state?

**Requirements**
- [ ] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1627%3A6507) requirements are met
- [ ] Classes use the BEM naming convention
- [ ] Design tokens are identified > proposed > implemented
- [ ] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by mjcarsjens** [comment]
Awaiting focus state design
