### ISSUE TITLE
Design: Breadcrumbs

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#74]
The Breadcrumbs component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1569%3A5671).

## Acceptance criteria
Uses links followed by arrows.

**Variants implemented**
- [ ] Normal
- [ ] Collapsed
- [ ] Icon

**States implemented**
- [ ] Normal
- [ ] Hover
- [ ] Focus
- [ ] Active

**Requirements**

- [ ] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1569%3A5671) requirements are met
- [ ] Classes use the BEM naming convention
- [ ] Design tokens are identified > proposed > implemented
- [ ] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by Robbert** [comment]
This component is an implementation of the Breadcrumb navigation component in NL Design System: nl-design-system/backlog#54

**Comment by bddjong** [comment]
Breadcrumb component is implemented in #574
