### ISSUE TITLE
Support for SCSS styles

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/denhaag#744]
# Description
In order to use a specific selection of Utrecht BEM classes, we need to support scss stylesheets so we can use `@include` and `@extend`.

## Required changes
Preferably, this change is gradual and won't require changes to all of our components. Rather, we want to be able to change specific stylesheets to `.scss` as we come across them or require the functionality.

The rollup config will need to be modified to support SASS.

**Comment by mjcarsjens** [comment]
@joostvanviegen is it done yet?
