### ISSUE TITLE
Design: Drawer

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#75]
The Drawer component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1633%3A6753).

**Requirements**
- [ ] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1633%3A6753) requirements are met
- [ ] Classes use the BEM naming convention
- [ ] Design tokens are identified > proposed > implemented
- [ ] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by mjcarsjens** [comment]
Design needs some more clarification
