### ISSUE TITLE
Design: Pagination

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#76]
The Pagination component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1673%3A231).

## Acceptance criteria
**Variants implemented**
- [ ] Normal
- [ ] Collapsed
- [ ] Icon

**States implemented**
- [ ] Normal
- [ ] Hover
- [ ] Focus
- [ ] Active

**Requirements**
- [ ] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1673%3A231) requirements are met
- [ ] Classes use the BEM naming convention
- [ ] Design tokens are identified > proposed > implemented
- [ ] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by mjcarsjens** [comment]
Awaiting reply in design for further specification of the requirements regarding how many items to show, when to show dots and which pages to show

**Comment by Robbert** [comment]
This component is an implementation of the Pagination component in NL Design System: nl-design-system/backlog#67
