### ISSUE TITLE
Design: Accordion

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#78]
The Accordion component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1585%3A0).

## Acceptance criteria

**Note:** In the design we have the Top, Middle and Bottom variant. These should however not be variants, but simply a design token for border-radius which sets the top border-radius on the first item, and the bottom border-radius on the last item.

**Variants**
- [ ] Opened
- [ ] Closed

**States implemented**
- [ ] Default 
- [ ] Hover
- [ ] Focus
- [ ] Active
- [ ] Disabled

**Requirements**
- [ ] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1585%3A0) requirements are met
- [ ] Classes use the BEM naming convention
- [ ] Design tokens are identified > proposed > implemented
- [ ] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by Robbert** [comment]
This component is an implementation of the Accordion component in NL Design System: nl-design-system/backlog#102
