### ISSUE TITLE
Design: cards/guides

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#84]
[Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1905%3A327)

**Comment by mjcarsjens** [comment]
Let's wait on the first card component before deciding how we implement these, i think these will simply become variants (so, same component with an extra html class: `...--guide`, since the actual content and behaviour is the same.
