### ISSUE TITLE
Merge components into one package

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#91]
Some components are published separately, but it makes no sense to use them without other components.

### Tasks
- [x] Create one package for the following components
  * Components into `tab`
    * tab
    * tabcontext
    * tablist
    * tabpanel
    * tabs
    * tabscrollbutton
  * Components into `menu`
    * menuitem
    * menulist
    * popover
    * popper
  * Components into `list`
    * listitem
    * listitemavatar
    * listitemicon
    * listitemsecondaryaction
    * listitemtext
    * listsubheader
  * Components into `avatar`
    * avatargroup
  * Components into `card`
    *  cardactions
    * cardcontent
    * cardheader
    * paper
  * Components into `accordion`
    * accordionactions
    * accordiondetails
    * accordionsummary 
- [ ] Remove the old packages

**Comment by mjcarsjens** [comment]
@GewoonMaarten @Gemeente-DenHaag/mdh-rysst 

Should we do this when working on the components when implementing the design? Seems like we could quite easily add this as a requirement to these specific components.

**Comment by GewoonMaarten** [comment]
This list of packages can be removed once the new packages are published:
```
@gemeente-denhaag/accordionactions
@gemeente-denhaag/accordiondetails
@gemeente-denhaag/accordionsummary
@gemeente-denhaag/avatargroup
@gemeente-denhaag/cardactions
@gemeente-denhaag/cardcontent
@gemeente-denhaag/cardheader
@gemeente-denhaag/gridlisttile
@gemeente-denhaag/gridlisttilebar
@gemeente-denhaag/listitem
@gemeente-denhaag/listitemavatar
@gemeente-denhaag/listitemicon
@gemeente-denhaag/listitemsecondaryaction
@gemeente-denhaag/listitemtext
@gemeente-denhaag/listsubheader
@gemeente-denhaag/menuitem
@gemeente-denhaag/menulist
@gemeente-denhaag/mobilestepper
@gemeente-denhaag/paper
@gemeente-denhaag/popover
@gemeente-denhaag/popper
@gemeente-denhaag/radiogroup
@gemeente-denhaag/step
@gemeente-denhaag/stepbutton
@gemeente-denhaag/stepconnector
@gemeente-denhaag/stepcontent
@gemeente-denhaag/stepicon
@gemeente-denhaag/steplabel
@gemeente-denhaag/tabcontext
@gemeente-denhaag/tablist
@gemeente-denhaag/tabpanel
@gemeente-denhaag/tabscrollbutton
@gemeente-denhaag/tabs
```
